# This file is generated in https://github.com/WeblateOrg/meta/
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
