[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=78.0.2"]

[dependency-groups]
dev = [
  "coverage>=3.6",
  "django-stubs-ext==6.0.9",
  "django-stubs==6.0.9",
  "mypy==2.4.0",
  "pre-commit",
  "pyright==1.1.414",
  "tox"
]

[project]
authors = [
  { email = "matiasaguirre@gmail.com", name = "Matias Aguirre" },
  { email = "michal@weblate.org", name = "Michal Čihař" }
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 5.2",
  "Framework :: Django :: 6.0",
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Internet"
]
dependencies = [
  "asgiref>=3.8.1",
  "Django>=5.2",
  "social-auth-core>=6.1.0,<7.0.0"
]
description = "Python Social Authentication, Django integration."
keywords = ["django", "oauth", "openid", "saml", "social auth"]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
name = "social-auth-app-django"
readme = "README.md"
requires-python = ">=3.10"
version = "7.1.0"

[project.optional-dependencies]
# This is present until pip implements supports for PEP 735
# see https://github.com/pypa/pip/issues/12963
dev = [
  "coverage>=3.6",
  "django-stubs-ext==6.0.9",
  "django-stubs==6.0.9",
  "mypy==2.4.0",
  "pre-commit",
  "pyright==1.1.414",
  "tox"
]

[project.urls]
Changelog = "https://github.com/python-social-auth/social-app-django/blob/master/CHANGELOG.md"
Funding = "https://opencollective.com/python-social-auth"
Homepage = "https://github.com/python-social-auth/social-app-django"

[tool.check-manifest]
ignore = [
  ".coveragerc",
  ".pre-commit-config.yaml",
  ".well-known/funding-manifest-urls",
  "tox.ini"
]

[tool.check-wheel-contents]
ignore = [
  "W004"  # Django migrations fail here
]

[tool.django-stubs]
django_settings_module = "tests.settings"
strict_settings = false

[tool.mypy]
check_untyped_defs = true
plugins = [
  "mypy_django_plugin.main"
]

[tool.pyright]
pythonVersion = "3.10"
reportAttributeAccessIssue = "none"
reportOptionalMemberAccess = "none"
reportPossiblyUnboundVariable = "none"

[tool.ruff]
# Ignore some well known paths
exclude = [
  "*.egg",
  ".tox",
  ".venv",
  "build",
  "db/env.py",
  "db/versions/*.py",
  "dist",
  "doc",
  "site"
]
line-length = 120
preview = true

[tool.ruff.lint]
ignore = [
  "ANN",  # TODO: Missing type annotations
  "boolean-default-value-positional-argument",  # TODO: Boolean default positional argument in function definition
  "boolean-positional-value-in-call",  # TODO: Boolean positional value in function call
  "D",  # TODO: Missing documentation
  "docstring-missing-exception",  # TODO
  "docstring-missing-returns",  # TODO
  "incorrect-blank-line-before-class",  # CONFIG: incompatible with D211
  "literal-membership",  # TODO!
  "missing-copyright-notice",  # TODO: Copyright not documented
  "missing-trailing-comma",  # CONFIG: incompatible with formatter
  "multi-line-summary-first-line",  # CONFIG: incompatible with D213
  "no-self-use",  # TODO
  "private-member-access",  # TODO!
  "PT",  # CONFIG: Not using pytest
  "too-many-locals",  # TODO
  "too-many-public-methods",  # TODO
  "unused-function-argument",  # TODO: Unused function argument (mostly for API compatibility)
  "unused-method-argument",  # TODO: Unused method argument (mostly for API compatibility)
  "used-dummy-variable"  # TODO
]
select = ["ALL"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.per-file-ignores]
"scripts/check_distribution.py" = ["implicit-namespace-package", "print"]
"social_django/migrations/*.py" = ["mutable-class-default"]
"tests/**.py" = ["django-model-without-dunder-str"]
"tests/settings.py" = ["PTH"]

[tool.rumdl]
disable = [
  # We do not enforce heading
  "first-line-heading",
  # Avoid length limit checks
  "line-length"
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-data]
social_django = ["py.typed", "templates/social_django/*.html"]

[tool.setuptools.packages.find]
include = ["social_django", "social_django.*"]
namespaces = false

[tool.tomlsort]
ignore_case = true
sort_inline_arrays = true
sort_inline_tables = true
sort_table_keys = true
spaces_before_inline_comment = 2
