# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0007_code_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='partial',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
