# Generated by Django 3.2.7 on 2021-09-14 15:48

from django.db import migrations, models
import django_kms.fields

class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialauth',
            name='actual_access_token',
            field=django_kms.fields.KMSEncryptedCharField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name='usersocialauth',
            name='actual_refresh_token',
            field=django_kms.fields.KMSEncryptedCharField(editable=True, null=True),
        ),
    ]
