# Generated by Django 3.2.7 on 2021-09-21 14:16

from django.db import migrations
import django_kms.fields
import social_django.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0011_tokens_separate_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialauth',
            name='actual_access_token',
            field=django_kms.fields.KMSEncryptedCharField(editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersocialauth',
            name='actual_refresh_token',
            field=django_kms.fields.KMSEncryptedCharField(editable=True, null=True),
        ),
    ]
