# Generated by Django 3.2.7 on 2021-09-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0012_auto_20210908_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialauth',
            old_name='access_token',
            new_name='user_access_token',
        ),
    ]
