# Generated by Django 3.2.7 on 2021-09-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0013_rename_access_token_usersocialauth_user_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocialauth',
            old_name='refresh_token',
            new_name='actual_access_token',
        ),
        migrations.RenameField(
            model_name='usersocialauth',
            old_name='user_access_token',
            new_name='actual_refresh_token',
        ),
    ]
