# Generated by Django 5.0.3 on 2024-03-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_django", "0015_rename_extra_data_new_usersocialauth_extra_data"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="UserSocialAuth",
            constraint=models.CheckConstraint(
                check=models.Q(("uid", ""), _negated=True),
                name="user_social_auth_uid_required",
            ),
        ),
    ]
