"""Freeze identifier defaults used before identifier-key tracking was introduced."""

from django.conf import settings
from django.db import migrations

# Audited against social-core 5.2.0. Keep this independent of installed backends
# and current configuration: both can change after associations were created.
# Google selected email by default through get_user_id(), not class ID_KEY.
OLD_ID_KEYS = {
    "amazon": "user_id",
    "angel": "id",
    "apple-id": "sub",
    "arcgis": "username",
    "asana": "id",
    "atlassian": "accountId",
    "auth0": "user_id",
    "auth0_openidconnect": "sub",
    "azuread-b2c-oauth2": "sub",
    "azuread-oauth2": "upn",
    "azuread-oauth2-v2": "upn",
    "azuread-tenant-oauth2": "sub",
    "azuread-v2-tenant-oauth2": "preferred_username",
    "battlenet-oauth2": "accountId",
    "behance": "id",
    "bitbucket-datacenter-oauth2": "id",
    "bitbucket-oauth2": "uuid",
    "box": "id",
    "bungie": "membership_id",
    "cas": "username",
    "cat": "sub",
    "cesid": "sub",
    "chatwork": "account_id",
    "chem": "sub",
    "cilogon-oauth2": "sub",
    "classlink": "UserId",
    "clever": "id",
    "coding": "id",
    "cognito": "username",
    "coinbase": "id",
    "coursera": "username",
    "culture": "sub",
    "dailymotion": "username",
    "daphne": "sub",
    "datagouv": "id",
    "datascience": "sub",
    "deezer": "name",
    "digitalocean": "uuid",
    "discogs": "id",
    "discord": "id",
    "discourse": "email",
    "disqus": "id",
    "docker": "user_id",
    "douban-oauth2": "id",
    "dribbble": "id",
    "drip": "email",
    "dropbox-oauth2": "uid",
    "e-infra_cz": "sub",
    "eduid": "sub",
    "eduid-staging": "sub",
    "egi-checkin": "sub",
    "elixir": "sub",
    "email": "email",
    "energy": "sub",
    "etsy": "user_id",
    "eventbrite": "id",
    "eveonline": "CharacterID",
    "evernote": "edam_userId",
    "evernote-sandbox": "edam_userId",
    "facebook": "id",
    "facebook-app": "id",
    "facebook-limited-login": "sub",
    "fairmat": "sub",
    "fedora-oidc": "sub",
    "fence": "username",
    "fitbit": "encodedId",
    "flat": "id",
    "flickr": "id",
    "foursquare": "id",
    "gitea": "id",
    "github": "id",
    "github-app": "id",
    "github-enterprise": "id",
    "github-enterprise-org": "id",
    "github-enterprise-team": "id",
    "github-org": "id",
    "github-team": "id",
    "gitlab": "id",
    "globus": "sub",
    "goclio": "id",
    "goclioeu": "id",
    "google-oauth": "email",
    "google-oauth2": "email",
    "google-onetap": "email",
    "google-openidconnect": "email",
    "grafana": "id",
    "helmholtz": "sub",
    "hubspot": "id",
    "immuno": "sub",
    "infraproxy": "sub",
    "infraproxy-staging": "sub",
    "ing": "sub",
    "instagram": "id",
    "justgiving": "userId",
    "kakao": "id",
    "keycloak": "username",
    "kick": "user_id",
    "lastfm": "name",
    "life_science": "sub",
    "line": "userId",
    "linkedin-mobile-oauth2": "id",
    "linkedin-oauth2": "id",
    "linkedin-openidconnect": "sub",
    "live": "id",
    "loginradius": "ID",
    "lyft": "id",
    "mailchimp": "user_id",
    "mailru": "email",
    "mailru-oauth2": "uid",
    "mapmyfitness": "id",
    "mardi": "sub",
    "matWerk": "sub",
    "mediawiki": "userID",
    "meetup": "id",
    "mendeley-oauth2": "id",
    "microsoft-graph": "id",
    "mineid": "id",
    "mixcloud": "username",
    "monzo": "id",
    "musicbrainz": "metabrainz_user_id",
    "nationbuilder": "id",
    "naver": "id",
    "objects": "sub",
    "odnoklassniki-app": "uid",
    "odnoklassniki-oauth2": "uid",
    "oidc": "sub",
    "okta-oauth2": "preferred_username",
    "okta-openidconnect": "preferred_username",
    "openshift": "uid",
    "openstreetmap-oauth2": "id",
    "opensuse": "nickname",
    "orbi": "id",
    "orcid": "orcid",
    "orcid-sandbox": "orcid",
    "osso": "id",
    "patreon": "id",
    "paypal-oauth2": "user_id",
    "paypal-oauth2-sandbox": "user_id",
    "phabricator": "id",
    "ping": "sub",
    "pinterest": "user_id",
    "pixelpin-openidconnect": "sub",
    "podio": "id",
    "punch": "sub",
    "pushbullet": "iden",
    "qiita": "id",
    "qq": "openid",
    "quizlet": "user_id",
    "reddit": "id",
    "salesforce-oauth2": "id",
    "salesforce-oauth2-sandbox": "id",
    "scistarter": "email",
    "seznam-oauth2": "oauth_user_id",
    "shopify": "shop",
    "simplelogin": "id",
    "sketchfab": "uid",
    "slack": "id",
    "soundcloud": "id",
    "spotify": "id",
    "stackoverflow": "user_id",
    "stocktwits": "id",
    "strava": "id",
    "stripe": "stripe_user_id",
    "surveymonkey": "id",
    "taobao": "taobao_user_id",
    "telegram": "id",
    "textplus": "sub",
    "trello": "username",
    "tripit": "id",
    "tumblr": "name",
    "twilio": "AccountSid",
    "twitch": "id",
    "twitter": "id",
    "twitter-oauth2": "id",
    "uber": "uuid",
    "ubuntu": "nickname",
    "uffd": "id",
    "universe": "id",
    "untappd": "id",
    "upwork": "id",
    "username": "username",
    "vault": "sub",
    "vend": "id",
    "vimeo": "id",
    "vimeo-oauth2": "uri",
    "vk-app": "id",
    "vk-oauth2": "id",
    "vk-openapi": "id",
    "weibo": "uid",
    "weixin": "openid",
    "weixinapp": "openid",
    "wlcg": "id",
    "xcs": "sub",
    "xing": "id",
    "yahoo-oauth2": "sub",
    "yammer": "id",
    "yammer-staging": "id",
    "yandex-oauth2": "id",
    "yandex-openid": "email",
    "yaru": "id",
    "zoom-oauth2": "id",
    "zotero": "userID",
}


def backfill_id_keys(apps, schema_editor):
    overrides = getattr(settings, "SOCIAL_AUTH_OLD_ID_KEYS", {})
    if not isinstance(overrides, dict):
        msg = "SOCIAL_AUTH_OLD_ID_KEYS must be a provider-to-historical-key mapping"
        raise TypeError(msg)
    old_keys = OLD_ID_KEYS | overrides
    social_auth = apps.get_model("social_django", "UserSocialAuth")
    provider_length = social_auth._meta.get_field("provider").max_length
    key_length = social_auth._meta.get_field("id_key").max_length
    for provider, key in old_keys.items():
        if not isinstance(provider, str) or not provider or len(provider) > provider_length:
            msg = "SOCIAL_AUTH_OLD_ID_KEYS contains an invalid provider"
            raise ValueError(msg)
        if key is not None and (not isinstance(key, str) or not key or len(key) > key_length):
            msg = "SOCIAL_AUTH_OLD_ID_KEYS keys must be nonempty strings fitting id_key, or None"
            raise ValueError(msg)
    manager = social_auth.objects.using(schema_editor.connection.alias)
    for provider, key in old_keys.items():
        if key is not None:
            manager.filter(provider=provider, id_key="").update(id_key=key)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [("social_django", "0019_oidc_nonce_lifetime")]
    operations = [migrations.RunPython(backfill_id_keys, migrations.RunPython.noop)]
