name: pre-commit check

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - uses: astral-sh/setup-uv@v5

    - name: pre-commit (uvx)
      run: uvx pre-commit run --all
      env:
        RUFF_OUTPUT_FORMAT: github
